### ISSUE TITLE
Idea of colorscheme inspired by the google chrome's devtool

### ISSUE THREAD

**Issue by vzytoi** [blackbirdtheme/vim#3]
Hi, I really like your work and I wanted to know if you ever thought of making a coloscheme inspired by the devtools of google chrome. Here are some screen shots :

- **JavaScript** : https://i.imgur.com/Zt6tG9J.png
- **HTML** : https://i.imgur.com/JZ32FbR.png
- **CSS** : https://i.imgur.com/YgtfZYG.png

Have a good day!

**Comment by gleich** [comment]
Hey vzytoi! I actually haven't but I am thinking of building a vim color scheme generator soon which should make it super easy to make vim themes. Let me know if you would be interested!

**Comment by vzytoi** [comment]
I would be super interested, let me know when i came out!
